/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'AK_base_linux_port.Debug+SSE-320-FVP' 
 * Target:  'Debug+SSE-320-FVP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.25.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u85
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.24.8 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define TF_LITE_DISABLE_X86_NEON 1
        //#define TF_LITE_STRIP_ERROR_STRINGS 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
